[env]
TERM = "xterm-256color"

[terminal.shell]
program = "zsh"
args = ["-c", "source ~/.zshrc; tmux new-session -A -s main"]

[window]
padding.x = 10
padding.y = 10
decorations = "None"
option_as_alt = "Both"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 13.0
